### ISSUE TITLE
High CPU Usage when calling client::connect in new thread

### ISSUE THREAD

**Issue by drojf** [Danr17/hass-rs#14]
I wanted to use hass-rs in a GUI application, and so wanted to run it in a new thread (I am using `async-std`).

I found that when calling client::connect in a new thread, it would cause high CPU usage, even when the task had already finished. However I think the application worked otherwise (I wouldn't have noticed the issue except that I saw high CPU usage)

Apologies if I'm not using async correctly and that is the problem, I only started using Rust async stuff for this application I'm working on.

## Reproduction Instructions

I prepared a minimal example to reproduce the high CPU usage. This example uses `async-std`. It starts a new thread, then inside the thread runs `client::connect()` within a `task::block_on`.

1. Clone this repo https://github.com/drojf/hass-rs-bug-report
2. Change the `client::connect(..)` call to have a valid home assistant host and port number
3. Run the program
4. Observe high CPU usage (The sleep() at the end of the program allows you to observe the high CPU usage). The high CPU usage will persist, even though the initial task/thread has already finished, until the program is closed.

----

Additionally, if you remove the sleep inside the thread (so client::connect runs, then immdiately closes itself), it will panic, but that might be unrelated to this issue. The error is `thread 'async-std/runtime' panicked at C:\Users\drojf\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hass-rs-0.2.0\src\wsconn.rs:300:70:`

[full_panic.txt](https://github.com/danrusei/hass-rs/files/13971470/full_panic.txt)

----

I also noticed in this example, if you set the wrong hostname, it will panic with
```
thread '<unnamed>' panicked at C:\Users\drojf\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hass-rs-0.2.0\src\wsconn.rs:38:49:
Can't connect to gateway: TungsteniteError(Io(Custom { kind: Uncategorized, error: VerboseError { source: Os { code: 11001, kind: Uncategorized, message: "No such host is known." }, message: "could not resolve address `(\"put_host_name_here\", 8123)`" } }))
```

**Comment by danrusei** [comment]
Hi Daniel,

Thanks for using my library and apologies for the inconvenience caused by high CPU usage.
Recently I redesigned / simplify the library API, due to several issues observed with the previous version.
The main change is that the web socket connection is moving to use responsibility, instead of managing by library.
You can check the latest version 0.3.0, and the examples provided in the Example folder, and see if it suits to you. 
If you still see issues or missing features please raise and issue.

**Comment by drojf** [comment]
I haven't tested it yet, but I did review how you changed the library, and I don't think this issue can happen anymore, so I'm closing this issue.
