### ISSUE TITLE
add Serialize derive to API structs

### ISSUE THREAD

**Issue by Winor** [Danr17/hass-rs#17]
Hey!
I wonder if it would be possible to add Serialize devire to the structs returned from the client (for example: HassEntity ) as I think it would be incredibly useful in cases when data needs to be sent as JSON for example. (If you think it would make sense to add Serialize derive to the structs for this reason..)

and I want to thank you for your wonderful work on this crate! I find it very useful and I am currently working on a tauri app that is using your crate and hopefullyI will have something functional to show soon.

Thank you :)

**Comment by danrusei** [comment]
thank you Winor, your use case makes totally sense to me. 
I saw that you have already raise a PR but wondering why to derive Serialize only as conditional attribute, I would instead derive Serialize as default.

**Comment by Winor** [comment]
No real reason tbh, I was just wondering if there was a reason you did not include it in the first place so I just went ahead and did that so I could keep working on my project and figured I would suggest this as a solution :)

**Comment by Winor** [comment]
Feel free to reject the PR and add Serialize as default instead

**Comment by danrusei** [comment]
I can do that, but I have limited access for a couple of days, if you could modify the PR I will merge it in the master.

**Comment by Winor** [comment]
Done!

**Comment by danrusei** [comment]
thank you for your contribution Winor !
