### ISSUE TITLE
client.get_services() does not work

### ISSUE THREAD

**Issue by stikonas** [Danr17/hass-rs#3]
```
    println!("Get Hass Services");
    match client.get_services().await {
        Ok(v) => println!("{:?}", v),
        Err(err) => println!("Oh no, an error: {}", err),
    }
```
results in 
```
Get Hass Services
Oh no, an error: Unable to deserialize the received value: missing field `example`
```

https://github.com/danrusei/hass-rs/blob/c6f46fe082abac70fb0c3e7a5d4e5f214e77490f/src/types/services.rs#L35

**Comment by danrusei** [comment]
Thanks for raising the issue. I could make the `example` field an Option<Value>. Would you be able to test it out and let me know if that works for you ?
Though in the [official JS client API](https://github.com/home-assistant/home-assistant-js-websocket/blob/291d22d0a8db154d3eda04b3ba044f3facc90cd5/lib/types.ts#L87) the example field is either a string, bool or number.

**Comment by stikonas** [comment]
> Thanks for raising the issue. I could make the `example` field an Option. Would you be able to test it out and let me know if that works for you ?
> Though in the [official JS client API](https://github.com/home-assistant/home-assistant-js-websocket/blob/291d22d0a8db154d3eda04b3ba044f3facc90cd5/lib/types.ts#L87) the example field is either a string, bool or number.

Sure, I can test.

**Comment by stikonas** [comment]
`pub example: Option<Value>` seems to work here.
